import type { PressRelease, MediaAsset, PRContact } from '@shared/types';
import { subDays, formatISO } from 'date-fns';
export const MOCK_CONTACT: PRContact = {
  id: 'contact-1',
  name: 'Jane Doe',
  title: 'Head of Communications',
  email: 'media@example.com',
  phone: '+1 (555) 123-4567',
};
export const MOCK_PRESS_RELEASES: PressRelease[] = [
  {
    id: 'pr-1',
    title: 'EdgePress Launches New Serverless CMS Platform',
    slug: 'edgepress-launches-new-serverless-cms-platform',
    summary: 'A revolutionary new platform designed for speed, security, and scalability, built entirely on the Cloudflare stack.',
    content: '<p>Today, EdgePress announced the official launch of its new serverless CMS platform. This platform leverages the full power of Cloudflare Workers and Durable Objects to provide an unparalleled content management experience.</p><h2>Key Features</h2><ul><li>Global distribution by default</li><li>Unmatched performance and low latency</li><li>Robust security features</li></ul>',
    tags: ['Product', 'Launch', 'Company News'],
    status: 'Published',
    publishAt: formatISO(subDays(new Date(), 1)),
    createdAt: formatISO(subDays(new Date(), 2)),
    updatedAt: formatISO(subDays(new Date(), 1)),
    attachments: [],
    contact: MOCK_CONTACT,
  },
  {
    id: 'pr-2',
    title: 'Company Announces Record Q3 Earnings',
    slug: 'company-announces-record-q3-earnings',
    summary: 'Driven by strong adoption of the new EdgePress platform, the company reports its most successful quarter to date.',
    content: '<p>The third quarter has been a monumental success, with revenue figures exceeding all projections. This growth is a testament to the hard work of our team and the innovative products we are bringing to market.</p>',
    tags: ['Financials', 'Company News'],
    status: 'Published',
    publishAt: formatISO(subDays(new Date(), 15)),
    createdAt: formatISO(subDays(new Date(), 16)),
    updatedAt: formatISO(subDays(new Date(), 15)),
    attachments: [],
    contact: MOCK_CONTACT,
  },
  {
    id: 'pr-3',
    title: 'New Partnership with Acme Corp to Enhance Enterprise Offerings',
    slug: 'new-partnership-with-acme-corp',
    summary: 'This strategic partnership will integrate Acme Corp\'s industry-leading analytics with the EdgePress CMS.',
    content: '<p>We are thrilled to announce a strategic partnership with Acme Corp. This collaboration will bring powerful new capabilities to our enterprise customers, combining our high-performance CMS with best-in-class data analytics.</p>',
    tags: ['Partnership', 'Enterprise'],
    status: 'Published',
    publishAt: formatISO(subDays(new Date(), 30)),
    createdAt: formatISO(subDays(new Date(), 31)),
    updatedAt: formatISO(subDays(new Date(), 30)),
    attachments: [],
    contact: MOCK_CONTACT,
  },
  {
    id: 'pr-4',
    title: 'Upcoming Feature Sneak Peek: AI-Powered Content Generation',
    slug: 'upcoming-feature-ai-content-generation',
    summary: 'A look into the future of EdgePress, where generative AI will assist content creators in crafting compelling narratives.',
    content: '<p>Get ready for the next evolution of content creation. Our team is hard at work on an AI-powered assistant that will be integrated directly into the EdgePress editor, helping you write faster and more effectively.</p>',
    tags: ['Product', 'AI', 'Future'],
    status: 'Draft',
    publishAt: formatISO(new Date()),
    createdAt: formatISO(subDays(new Date(), 5)),
    updatedAt: formatISO(subDays(new Date(), 1)),
    attachments: [],
    contact: MOCK_CONTACT,
  },
];
export const MOCK_ASSETS: MediaAsset[] = [
    { id: 'asset-1', url: '#', filename: 'logo-dark.svg', fileType: 'image/svg+xml', size: 15000, label: 'Logo (Dark)', category: 'logo' },
    { id: 'asset-2', url: '#', filename: 'logo-light.svg', fileType: 'image/svg+xml', size: 15000, label: 'Logo (Light)', category: 'logo' },
    { id: 'asset-3', url: '#', filename: 'product-screenshot-1.png', fileType: 'image/png', size: 850000, label: 'Dashboard Screenshot', category: 'product' },
    { id: 'asset-4', url: '#', filename: 'ceo-headshot.jpg', fileType: 'image/jpeg', size: 1200000, label: 'CEO Headshot', category: 'executive' },
];